// GENERATED by a temporary vitest file in the actual/ checkout — do not edit by hand.
// Regenerate per docs/superpowers/plans/2026-07-17-post-scheduled-transactions.md Task 2.
// swiftlint:disable all
let recurrenceFixturesJSON = #"""
[
  {
    "name": "daily interval 1, query mid-stream",
    "config": {
      "frequency": "daily",
      "start": "2026-01-01"
    },
    "queryDate": "2026-03-15",
    "expected": "2026-03-15"
  },
  {
    "name": "daily interval 3, query between occurrences",
    "config": {
      "frequency": "daily",
      "interval": 3,
      "start": "2026-01-01"
    },
    "queryDate": "2026-01-05",
    "expected": "2026-01-07"
  },
  {
    "name": "daily interval 3, query exactly on an occurrence",
    "config": {
      "frequency": "daily",
      "interval": 3,
      "start": "2026-01-01"
    },
    "queryDate": "2026-01-07",
    "expected": "2026-01-07"
  },
  {
    "name": "daily interval 1, query before start",
    "config": {
      "frequency": "daily",
      "start": "2026-08-01"
    },
    "queryDate": "2026-07-17",
    "expected": "2026-08-01"
  },
  {
    "name": "weekly interval 1, start Wednesday, query Friday same week",
    "config": {
      "frequency": "weekly",
      "start": "2026-01-07"
    },
    "queryDate": "2026-01-09",
    "expected": "2026-01-14"
  },
  {
    "name": "weekly interval 1, query exactly on an occurrence",
    "config": {
      "frequency": "weekly",
      "start": "2026-01-07"
    },
    "queryDate": "2026-01-14",
    "expected": "2026-01-14"
  },
  {
    "name": "weekly interval 2, query in the off week (anchoring)",
    "config": {
      "frequency": "weekly",
      "interval": 2,
      "start": "2026-01-07"
    },
    "queryDate": "2026-01-15",
    "expected": "2026-01-21"
  },
  {
    "name": "weekly interval 2, query day after first occurrence (anchoring)",
    "config": {
      "frequency": "weekly",
      "interval": 2,
      "start": "2026-01-07"
    },
    "queryDate": "2026-01-08",
    "expected": "2026-01-21"
  },
  {
    "name": "weekly interval 4, query mid-cycle",
    "config": {
      "frequency": "weekly",
      "interval": 4,
      "start": "2026-01-07"
    },
    "queryDate": "2026-02-01",
    "expected": "2026-02-04"
  },
  {
    "name": "monthly no-pattern, start day 1, query mid-Feb",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01"
    },
    "queryDate": "2026-02-15",
    "expected": "2026-03-01"
  },
  {
    "name": "monthly no-pattern, start day 15, query day after start",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15"
    },
    "queryDate": "2026-01-16",
    "expected": "2026-02-15"
  },
  {
    "name": "monthly no-pattern, start day 29, query in non-leap Feb",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-29"
    },
    "queryDate": "2026-02-01",
    "expected": "2026-03-29"
  },
  {
    "name": "monthly no-pattern, start day 30, query in Feb",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-30"
    },
    "queryDate": "2026-02-01",
    "expected": "2026-03-30"
  },
  {
    "name": "monthly no-pattern, start day 31, query in Feb (short-month decision)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-31"
    },
    "queryDate": "2026-02-01",
    "expected": "2026-03-31"
  },
  {
    "name": "monthly no-pattern, start day 31, query in April (30-day month)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-31"
    },
    "queryDate": "2026-04-01",
    "expected": "2026-05-31"
  },
  {
    "name": "monthly no-pattern interval 3, query in skipped month (anchoring)",
    "config": {
      "frequency": "monthly",
      "interval": 3,
      "start": "2026-01-10"
    },
    "queryDate": "2026-02-15",
    "expected": "2026-04-10"
  },
  {
    "name": "monthly days 1 and 15, query between them (next is 1st)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 1
        },
        {
          "type": "day",
          "value": 15
        }
      ]
    },
    "queryDate": "2026-01-20",
    "expected": "2026-02-01"
  },
  {
    "name": "monthly days 1 and 15, query between them (next is 15th)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 1
        },
        {
          "type": "day",
          "value": 15
        }
      ]
    },
    "queryDate": "2026-02-02",
    "expected": "2026-02-15"
  },
  {
    "name": "monthly day -1 (last day), query mid-Feb non-leap",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": -1
        }
      ]
    },
    "queryDate": "2026-02-10",
    "expected": "2026-02-28"
  },
  {
    "name": "monthly day 31 pattern, query in Feb (short-month behavior)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 31
        }
      ]
    },
    "queryDate": "2026-02-01",
    "expected": "2026-03-31"
  },
  {
    "name": "monthly mixed day 5 and day -1, query after the 5th",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 5
        },
        {
          "type": "day",
          "value": -1
        }
      ]
    },
    "queryDate": "2026-01-06",
    "expected": "2026-01-31"
  },
  {
    "name": "monthly mixed day 5 and day -1, query at month boundary",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 5
        },
        {
          "type": "day",
          "value": -1
        }
      ]
    },
    "queryDate": "2026-02-01",
    "expected": "2026-02-05"
  },
  {
    "name": "monthly 2nd Tuesday, query day after January hit",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "TU",
          "value": 2
        }
      ]
    },
    "queryDate": "2026-01-14",
    "expected": "2026-02-10"
  },
  {
    "name": "monthly last Friday, query at start of month",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "FR",
          "value": -1
        }
      ]
    },
    "queryDate": "2026-01-01",
    "expected": "2026-01-30"
  },
  {
    "name": "monthly 1st Monday interval 2, query in skipped month",
    "config": {
      "frequency": "monthly",
      "interval": 2,
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "MO",
          "value": 1
        }
      ]
    },
    "queryDate": "2026-02-01",
    "expected": "2026-03-02"
  },
  {
    "name": "monthly union day 10 + 1st Friday, query when day pattern is next",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 10
        },
        {
          "type": "FR",
          "value": 1
        }
      ]
    },
    "queryDate": "2026-01-03",
    "expected": "2026-01-10"
  },
  {
    "name": "monthly union day 10 + 1st Friday, query when weekday pattern is next",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-01",
      "patterns": [
        {
          "type": "day",
          "value": 10
        },
        {
          "type": "FR",
          "value": 1
        }
      ]
    },
    "queryDate": "2026-01-11",
    "expected": "2026-02-06"
  },
  {
    "name": "yearly interval 1, query after this year occurrence",
    "config": {
      "frequency": "yearly",
      "start": "2026-03-10"
    },
    "queryDate": "2026-06-01",
    "expected": "2027-03-10"
  },
  {
    "name": "yearly interval 2, query in off year",
    "config": {
      "frequency": "yearly",
      "interval": 2,
      "start": "2026-03-10"
    },
    "queryDate": "2027-01-01",
    "expected": "2028-03-10"
  },
  {
    "name": "yearly Feb 29 start, query in following non-leap year",
    "config": {
      "frequency": "yearly",
      "start": "2024-02-29"
    },
    "queryDate": "2025-01-01",
    "expected": "2028-02-29"
  },
  {
    "name": "yearly Feb 29 start, query before start",
    "config": {
      "frequency": "yearly",
      "start": "2024-02-29"
    },
    "queryDate": "2024-01-01",
    "expected": "2024-02-29"
  },
  {
    "name": "skipWeekend after: monthly occurrence on Saturday moves to Monday",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-31",
      "skipWeekend": true,
      "weekendSolveMode": "after"
    },
    "queryDate": "2026-01-01",
    "expected": "2026-02-02"
  },
  {
    "name": "skipWeekend before: monthly occurrence on Saturday moves to Friday",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-31",
      "skipWeekend": true,
      "weekendSolveMode": "before"
    },
    "queryDate": "2026-01-01",
    "expected": "2026-01-30"
  },
  {
    "name": "skipWeekend before: solve moves result before the query date",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-31",
      "skipWeekend": true,
      "weekendSolveMode": "before"
    },
    "queryDate": "2026-01-31",
    "expected": "2026-01-30"
  },
  {
    "name": "skipWeekend after: weekly occurrence on Sunday moves to Monday",
    "config": {
      "frequency": "weekly",
      "start": "2026-01-04",
      "skipWeekend": true,
      "weekendSolveMode": "after"
    },
    "queryDate": "2026-01-02",
    "expected": "2026-01-05"
  },
  {
    "name": "skipWeekend after: weekday occurrence unaffected",
    "config": {
      "frequency": "weekly",
      "start": "2026-01-07",
      "skipWeekend": true,
      "weekendSolveMode": "after"
    },
    "queryDate": "2026-01-05",
    "expected": "2026-01-07"
  },
  {
    "name": "end after 3 occurrences: query before exhaustion",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "after_n_occurrences",
      "endOccurrences": 3
    },
    "queryDate": "2026-02-01",
    "expected": "2026-02-15"
  },
  {
    "name": "end after 3 occurrences: query exactly on the last occurrence",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "after_n_occurrences",
      "endOccurrences": 3
    },
    "queryDate": "2026-03-15",
    "expected": "2026-03-15"
  },
  {
    "name": "end after 3 occurrences: query after exhaustion (fallback to last)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "after_n_occurrences",
      "endOccurrences": 3
    },
    "queryDate": "2026-05-01",
    "expected": "2026-03-15"
  },
  {
    "name": "end on date: query before end",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "on_date",
      "endDate": "2026-04-20"
    },
    "queryDate": "2026-02-01",
    "expected": "2026-02-15"
  },
  {
    "name": "end on date: query exactly on final occurrence",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "on_date",
      "endDate": "2026-04-20"
    },
    "queryDate": "2026-04-15",
    "expected": "2026-04-15"
  },
  {
    "name": "end on date: query after end (fallback to last)",
    "config": {
      "frequency": "monthly",
      "start": "2026-01-15",
      "endMode": "on_date",
      "endDate": "2026-04-20"
    },
    "queryDate": "2026-06-01",
    "expected": "2026-04-15"
  },
  {
    "name": "end on date before start: no occurrences at all",
    "config": {
      "frequency": "monthly",
      "start": "2026-03-25",
      "endMode": "on_date",
      "endDate": "2026-01-25"
    },
    "queryDate": "2026-01-01",
    "expected": null
  },
  {
    "name": "monthly, query well before start returns first occurrence",
    "config": {
      "frequency": "monthly",
      "start": "2026-05-10"
    },
    "queryDate": "2026-01-01",
    "expected": "2026-05-10"
  },
  {
    "name": "monthly, query exactly on start returns start",
    "config": {
      "frequency": "monthly",
      "start": "2026-05-10"
    },
    "queryDate": "2026-05-10",
    "expected": "2026-05-10"
  }
]
"""#
